### ISSUE TITLE
Getting a blank screen trying to add book to reader

### ISSUE THREAD

**Issue by aaron-meyers** [mathewthe2/immersion_reader#12]
I just installed the app, went to Reader and clicked the '+'. I just get a blank white screen. If I tap on Reader at the bottom again it goes back to that screen with the EPUB reader and Browser Plus sections.

Under the Discover tab, I can click on content and it opens a webpage from Immersion Kit in an embedded browser. There doesn't seem to be any special functionality though - that is, no pop-up dictionary, just the normal iOS selection behavior (can Look Up in the system dictionary etc).

I'm using an iPad mini 5th gen running iPadOS 16.5.1 (20F75).

**Comment by mathewthe2** [comment]
I just tested the latest version on a physical iPad Pro running 16.4.1 and I'm not able to reproduce your issues.

Do you mind testing it on XCode and seeing if the same issues persist with an emulator?

**Comment by aaron-meyers** [comment]
Sorry I don't have a Mac (or any experience with XCode). Maybe it's something introduced in iPad 16.5.x? Not sure if you're willing to update your iPad Pro but I wonder if it would repro on 16.5.1. I also have the Rapid Response security update installed that was released last week.

**Comment by mathewthe2** [comment]
I just updated to the latest release of 16.5.1, and everything is working so far. I will have to close this issue if there is not a way to reproduce the issue.

**Comment by aaron-meyers** [comment]
I'm happy to provide any diagnostics that would help if/when that's available. It looks like your app doesn't currently have a diagnostic logging option but if you add something like this later I can certainly use that. My only other idea is that maybe it has something to do with being an iPad mini (opposite end of the screen size vs iPad Pro) but that doesn't seem very likely. Not sure how else to help reproduce the issue for you, assuming you don't want to come to Seattle and see it ;)

FWIW I also noticed that you can swipe from the left to get from the blank screen back to the Reader tab. Here's a screenshot mid-swipe:

![Screenshot 2023-07-18 at 9 44 18 PM](https://github.com/mathewthe2/immersion_reader/assets/13340718/c3c5ac1a-e674-4891-99f8-233326e274b5)

**Comment by mathewthe2** [comment]
I reinstalled the app on my iPad and there doesn't seem to be any issues.

I'll think about diagnostics. It might be something that has to pass through Apple's verification process.

**Comment by mathewthe2** [comment]
I was able to reproduce a similar symptom after messing around with the builds on an emulator, but the issue was resolved after reinstalling the app. I'm sure you've tried re-installing the app already, so there could be another cause for your issue.

**Comment by aaron-meyers** [comment]
Yeah reinstalling didn't help. I finally gave in and bought a Mac mini last week so I'll find some time to figure out how to run it in XCode.

**Comment by lcmortech** [comment]
I have this same issue on the ipad mini 5, even though it works on my iphone X. Reinstalling did not solve the issue.
